version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: auth_service_java_db
    environment:
      POSTGRES_DB: backend_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: auth_service_java_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
