sonar.projectKey=teilorbarcelos_auth-service-java
sonar.projectName=Auth Service Java
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.exclusions=**/target/**,**/db/migration/**
sonar.test.inclusions=**/*Test*.java
sonar.java.coveragePlugin=jacoco
sonar.jacoco.reportPaths=target/jacoco-report/jacoco.xml
sonar.host.url=http://localhost:9000
